### PR TITLE
globalization behavior of value providers

### LINKED ISSUE #15829: Add info about globalization behavior of value providers
We should add information that answers questions like https://github.com/aspnet/AspNetCore/issues/17324 to this section.

The answer in short: Our route value provider, and query string value provider treat values as **invariant culture**. Put another way, we expect that URLs are culture-invariant in MVC. In contrast, values coming from form data do a culture-sensitive conversion. This is on purpose so that URLs are shareable across locales.

If you want to change this behavior: 
- Inherit from `IValueProviderFactory` 
- Copy the code from [QueryStringValueProviderFactory](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs) or [RouteValueValueProviderFactory](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/RouteValueProviderFactory.cs)
- Replace the [culture value](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs#L30) passed to the value provider constructor with `CultureInfo.CurrentCulture`
- Replace the default value provider factory in MVC options with your new one

```C#

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(options =>
            {
                var index = options.ValueProviderFactories.IndexOf(options.ValueProviderFactories.OfType<QueryStringValueProviderFactory>().Single());
                options.ValueProviderFactories[index] = new CulturedQueryStringValueProviderFactory();
            });
        }

...
        public class CulturedQueryStringValueProviderFactory : IValueProviderFactory
        {
            /// <inheritdoc />
            public Task CreateValueProviderAsync(ValueProviderFactoryContext context)
            {
                if (context == null)
                {
                    throw new ArgumentNullException(nameof(context));
                }

                var query = context.ActionContext.HttpContext.Request.Query;
                if (query != null && query.Count > 0)
                {
                    var valueProvider = new QueryStringValueProvider(
                        BindingSource.Query,
                        query,
                        CultureInfo.CurrentCulture);

                    context.ValueProviders.Add(valueProvider);
                }

                return Task.CompletedTask;
            }
        }

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24f48f8-6c4d-ecda-6ce6-a7826d396e99
* Version Independent ID: 9c4af557-8d06-4c6c-ad2a-0dd234547563
* Content: [Model Binding in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-3.0)
* Content Source: [aspnetcore/mvc/models/model-binding.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/mvc/models/model-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

### PR DESCRIPTION
**Pull request by Rick-Anderson**
Fixes #15829

@newbienewbie  please review. I tried to make the H2's have SEO power so someone in your position could find it.

### CODE REVIEW

File: aspnetcore/mvc/models/model-binding/samples/StartupMB.cs [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+                    BindingSource.Query,
+                    query,
+                    CultureInfo.CurrentCulture);
+
+                context.ValueProviders.Add(valueProvider);
+            }
+
+            return Task.CompletedTask;
+        }
+        #endregion
```
Comment (newbienewbie) [inline aspnetcore/mvc/models/model-binding/samples/StartupMB.cs]: @Rick-Anderson  Should this line be placed after the 89th line?

File: aspnetcore/mvc/models/model-binding.md [hunk 2]
```diff
@@ -376,14 +376,24 @@ For `Dictionary` targets, model binding looks for matches to *parameter_name* or
...
 * Expect that URLs are culture-invariant.
 
-In contrast, values coming from form data do a culture-sensitive conversion. This is on purpose so that URLs are shareable across locales.
+In contrast, values coming from form data undergo a culture-sensitive conversion. This is by design so that URLs are shareable across locales.
+
+To make the ASP.NET Core route value provider and query string value provider undergo a culture-sensitive conversion:
+
+* Inherit from <xref:Microsoft.AspNetCore.Mvc.ModelBinding.IValueProviderFactory>
+* Copy the code from [QueryStringValueProviderFactory](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs) or [RouteValueValueProviderFactory](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/RouteValueProviderFactory.cs)
+* Replace the [culture value](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs#L30) passed to the value provider constructor with [CultureInfo.CurrentCulture](xref:System.Globalization.CultureInfo.CurrentCulture)
```
Comment (newbienewbie) [inline aspnetcore/mvc/models/model-binding.md]: @Rick-Anderson Should we use a permelink in case someone adds/removes a line before this 30th line? i.e: https://github.com/aspnet/AspNetCore/blob/e625fe29b049c60242e8048b4ea743cca65aa7b5/src/Mvc/Mvc.Core/src/ModelBinding/QueryStringValueProviderFactory.cs#L30

**Comment by Rick-Anderson** [comment]
@newbienewbie  thanks for your help.
